import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { rootDir } from "./helpers";

/**
 * `src/registry/index.ts` is generated by `scripts/generate-registry.mjs` and
 * carries a "do NOT edit this file manually" banner. Nothing enforced that.
 *
 * Adding a component to `src/registry/ui/` without regenerating is silent: the
 * file builds, the component is unreachable, and `<ComponentPreview>` renders
 * nothing at all rather than erroring. These are the checks that make
 * forgetting loud, in the same spirit as `scripts/check-sidebar.mjs`.
 */

const registryDir = join(rootDir, "src/registry/ui");
const indexPath = join(rootDir, "src/registry/index.ts");

function componentFiles(): string[] {
  return readdirSync(registryDir)
    .filter((file) => file.endsWith(".tsx") || file.endsWith(".ts"))
    .map((file) => file.replace(/\.tsx?$/, ""))
    .sort();
}

function mappedIds(): string[] {
  const source = readFileSync(indexPath, "utf-8");
  return [...source.matchAll(/^\s*"([^"]+)":\s*\(\)\s*=>\s*import\(/gm)].map(
    (match) => match[1],
  );
}

describe("Yumma UI registry", () => {
  it("maps every component file", () => {
    const missing = componentFiles().filter(
      (id) => !new Set(mappedIds()).has(id),
    );

    expect(
      missing,
      "run `node scripts/generate-registry.mjs` to pick these up",
    ).toEqual([]);
  });

  it("does not map components that no longer exist", () => {
    const files = new Set(componentFiles());
    const stale = mappedIds().filter((id) => !files.has(id));

    expect(
      stale,
      "run `node scripts/generate-registry.mjs` to drop these",
    ).toEqual([]);
  });

  it("has no duplicate ids", () => {
    const ids = mappedIds();
    const seen = new Set<string>();
    const duplicates = ids.filter((id) => !seen.add(id));

    expect(duplicates).toEqual([]);
  });

  it("points every id at its own file", () => {
    const source = readFileSync(indexPath, "utf-8");
    const mismatched = [
      ...source.matchAll(
        /^\s*"([^"]+)":\s*\(\)\s*=>\s*import\("\.\/ui\/([^"]+)"\)/gm,
      ),
    ]
      .filter(([, id, target]) => id !== target)
      .map(([, id, target]) => `${id} -> ${target}`);

    expect(mismatched).toEqual([]);
  });

  // `iconSide` on 5 components and `iconPosition` on 9 were one prop with two
  // names, same `leading`/`trailing` values. Two names for one concept is the
  // shape of that bug, so the rule is stated rather than the pair banned.
  it("uses one name per concept across components", () => {
    const names = new Set<string>();
    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      for (const prop of meta.props ?? []) names.add(prop.name);
    }

    const byStem = new Map<string, string[]>();
    for (const name of names) {
      const stem = name.replace(/(Side|Position|Placement|Align)$/, "");
      if (stem === name) continue;
      byStem.set(stem, [...(byStem.get(stem) ?? []), name]);
    }

    const split = [...byStem.values()].filter((group) => group.length > 1);

    expect(split).toEqual([]);
  });

  // A conflict rule naming a prop that is not there is a rule that never
  // fires, in silence - the same failure as an unknown icon name.
  it("points every conflict rule at a prop that exists", () => {
    const broken: string[] = [];

    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      const names = new Set(
        (meta.props ?? []).map((p: { name: string }) => p.name),
      );
      for (const prop of meta.props ?? []) {
        for (const rule of prop.conflictsWith ?? []) {
          if (!names.has(rule.prop)) {
            broken.push(`${file}: ${prop.name} -> ${rule.prop}`);
          }
          const forms = ["is", "not", "set"].filter((key) => key in rule);
          if (forms.length !== 1) {
            broken.push(`${file}: ${prop.name} -> ${forms.length} forms`);
          }
        }
      }
    }

    expect(broken).toEqual([]);
  });

  // The playground shows the block; the source should say it too, or someone
  // reading the component has no idea the prop can go quiet.
  it("documents every conflict rule in the component", () => {
    const undocumented: string[] = [];

    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      const component = join(
        rootDir,
        "src/registry/ui",
        file.replace(".json", ".tsx"),
      );
      if (!existsSync(component)) continue;
      const source = readFileSync(component, "utf-8");

      for (const prop of meta.props ?? []) {
        if (!prop.conflictsWith) continue;
        const declaration = source.indexOf(`  ${prop.name}?:`);
        if (declaration === -1) continue;
        const above = source.slice(0, declaration);
        if (!/\*\/\s*$/.test(above)) {
          undocumented.push(`${file}: ${prop.name}`);
        }
      }
    }

    expect(undocumented).toEqual([]);
  });

  // The other half of the rule. `count` was a ReactNode badge on Badge and a
  // number of stars on Rating; `separator` was a boolean on Accordion and an
  // enum on Breadcrumb. One name with two control kinds is one name with two
  // meanings, which reads as one API and is not. Generic names whose shape is
  // meant to vary by component are listed out.
  it("gives one name one meaning across components", () => {
    const GENERIC = new Set([
      "value",
      "defaultValue",
      "onValueChange",
      "items",
      "options",
      "label",
      "description",
      "size",
      "icon",
    ]);

    const kinds = new Map<string, Set<string>>();
    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      for (const prop of meta.props ?? []) {
        if (GENERIC.has(prop.name)) continue;
        kinds.set(
          prop.name,
          (kinds.get(prop.name) ?? new Set<string>()).add(prop.type),
        );
      }
    }

    const split = [...kinds]
      .filter(([, types]) => types.size > 1)
      .map(([name, types]) => `${name}: ${[...types].sort().join(" | ")}`);

    expect(split).toEqual([]);
  });

  // `"false"` is truthy, so a boolean default written as a string seeds the
  // playground with the prop switched on. Four components rendered disabled.
  it("declares boolean defaults as booleans", () => {
    const wrong: string[] = [];

    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      for (const prop of meta.props ?? []) {
        if (prop.type === "boolean" && typeof prop.default === "string") {
          wrong.push(`${file}: ${prop.name}`);
        }
      }
    }

    expect(wrong).toEqual([]);
  });

  // Same shape one level down: a schema can name any icon it likes, but
  // `resolveIcons` only knows the ones in `EXAMPLE_ICONS`, and an unknown name
  // resolves to `undefined` in silence - the toolbar's toggles simply did not
  // render, with nothing to say why.
  it("resolves every icon a schema names", () => {
    const known = new Set(
      (
        readFileSync(join(rootDir, "src/utils/demo.tsx"), "utf-8").match(
          /export const EXAMPLE_ICONS[^{]*\{[^}]*\}[^{]*\{([^}]*)\}/,
        )?.[1] ?? ""
      )
        .split(",")
        .map((entry) => entry.trim())
        .filter(Boolean),
    );

    expect(known.size).toBeGreaterThan(0);

    const named: string[] = [];
    const walk = (value: unknown) => {
      if (Array.isArray(value)) return value.forEach(walk);
      if (typeof value !== "object" || value === null) return;
      const marker = (value as Record<string, unknown>).$icon;
      if (typeof marker === "string") named.push(marker);
      for (const nested of Object.values(value)) walk(nested);
    };

    const missing: string[] = [];
    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      named.length = 0;
      walk(meta);
      for (const prop of meta.props ?? []) {
        if (prop.exampleIcon) named.push(prop.exampleIcon);
      }
      for (const name of named) {
        if (!known.has(name)) missing.push(`${file}: ${name}`);
      }
    }

    expect(missing).toEqual([]);
  });

  // The snippet prints whatever `childrenExample` names, but the stage can only
  // render a component in `CHILD_COMPONENTS`. A name in one and not the other
  // is the code block lying again, in the other direction.
  it("renders every child the snippet prints", () => {
    const known = new Set(
      (
        readFileSync(join(rootDir, "src/utils/demo.tsx"), "utf-8").match(
          /const CHILD_COMPONENTS[^{]*\{([^}]*)\}/,
        )?.[1] ?? ""
      )
        .split(",")
        .map((entry) => entry.trim())
        .filter(Boolean),
    );

    const missing: string[] = [];
    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      for (const child of meta.childrenExample ?? []) {
        if (child.text !== undefined) continue;
        if (!known.has(child.component))
          missing.push(`${file}: ${child.component}`);
      }
    }

    expect(missing).toEqual([]);
  });

  /** The shape vocabulary in AGENTS.md, as far as a regex can hold it. */
  it("keeps one meaning per shape name", () => {
    const wrong: string[] = [];
    const uiDir = join(rootDir, "src/registry/ui");

    for (const file of readdirSync(uiDir).filter((f) => f.endsWith(".tsx"))) {
      const source = readFileSync(join(uiDir, file), "utf-8");

      for (const [, name, body] of source.matchAll(
        /const (\w*SHAPES?\w*): Record<[^>]+> = \{([\s\S]*?)\n\};/g,
      )) {
        const entries = new Map(
          [...body.matchAll(/(\w+):\s*"([^"]*)"/g)].map((m) => [m[1], m[2]]),
        );

        const squircle = entries.get("squircle");
        if (squircle !== undefined && !squircle.includes("cs-s")) {
          wrong.push(`${file}:${name} squircle is not a squircle`);
        }

        const pill = entries.get("pill");
        const rounded = entries.get("rounded");
        if (pill !== undefined && rounded !== undefined && pill === rounded) {
          wrong.push(`${file}:${name} pill and rounded are the same`);
        }
        if (pill !== undefined && !pill.includes("br-9999")) {
          wrong.push(`${file}:${name} pill is not fully round`);
        }
      }
    }

    expect(wrong).toEqual([]);
  });

  /**
   * An example key the component's own type does not have is a field nothing
   * reads. Radio carried `icon` markers for months after the icons were taken
   * out, and the props table documented them the whole time.
   */
  it("keeps example objects to the fields their type declares", () => {
    const wrong: string[] = [];
    const metaDir = join(rootDir, "src/registry/meta");
    const uiDir = join(rootDir, "src/registry/ui");

    for (const file of readdirSync(metaDir).filter((f) =>
      f.endsWith(".json"),
    )) {
      const id = file.replace(/\.json$/, "");
      const component = join(uiDir, `${id}.tsx`);
      if (!existsSync(component)) continue;

      const source = readFileSync(component, "utf-8");
      const meta = JSON.parse(readFileSync(join(metaDir, file), "utf-8"));

      for (const prop of meta.props ?? []) {
        const named = /^(\w+)\[\]$/.exec(prop.typeName ?? "");
        if (!named || !Array.isArray(prop.example)) continue;

        const declared = new RegExp(
          `export interface ${named[1]}\\s*\\{([\\s\\S]*?)\\n\\}`,
        ).exec(source);
        if (!declared) continue;

        const fields = new Set(
          [...declared[1].matchAll(/^\s{2}(\w+)\??:/gm)].map((m) => m[1]),
        );

        for (const entry of prop.example) {
          if (typeof entry !== "object" || entry === null) continue;
          for (const key of Object.keys(entry)) {
            if (!fields.has(key)) {
              wrong.push(`${id}:${prop.name} has ${key}, ${named[1]} does not`);
            }
          }
        }
      }
    }

    expect(wrong).toEqual([]);
  });

  /** Round means one of these; square means any of these. */
  it("gives the radio no shape prop", () => {
    const meta = JSON.parse(
      readFileSync(join(rootDir, "src/registry/meta/radio.json"), "utf-8"),
    );
    const source = readFileSync(
      join(rootDir, "src/registry/ui/radio.tsx"),
      "utf-8",
    );

    expect(meta.props.map((prop: { name: string }) => prop.name)).not.toContain(
      "shape",
    );
    // The word is allowed in prose; the prop, its type and its map are not.
    expect(source).not.toMatch(/shape\s*[?:=]|SHAPES|\bShape\b/);
  });

  it("is not empty", () => {
    expect(mappedIds().length).toBeGreaterThan(0);
  });
});
