import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { rootDir } from "./helpers";

/**
 * `src/registry/index.ts` is generated by `scripts/generate-registry.mjs` and
 * carries a "do NOT edit this file manually" banner. Nothing enforced that.
 *
 * Adding a component to `src/registry/ui/` without regenerating is silent: the
 * file builds, the component is unreachable, and `<ComponentPreview>` renders
 * nothing at all rather than erroring. These are the checks that make
 * forgetting loud, in the same spirit as `scripts/check-sidebar.mjs`.
 */

const registryDir = join(rootDir, "src/registry/ui");
const indexPath = join(rootDir, "src/registry/index.ts");

function componentFiles(): string[] {
  return readdirSync(registryDir)
    .filter((file) => file.endsWith(".tsx") || file.endsWith(".ts"))
    .map((file) => file.replace(/\.tsx?$/, ""))
    .sort();
}

function mappedIds(): string[] {
  const source = readFileSync(indexPath, "utf-8");
  return [...source.matchAll(/^\s*"([^"]+)":\s*\(\)\s*=>\s*import\(/gm)].map(
    (match) => match[1],
  );
}

describe("Yumma UI registry", () => {
  it("maps every component file", () => {
    const missing = componentFiles().filter(
      (id) => !new Set(mappedIds()).has(id),
    );

    expect(
      missing,
      "run `node scripts/generate-registry.mjs` to pick these up",
    ).toEqual([]);
  });

  it("does not map components that no longer exist", () => {
    const files = new Set(componentFiles());
    const stale = mappedIds().filter((id) => !files.has(id));

    expect(
      stale,
      "run `node scripts/generate-registry.mjs` to drop these",
    ).toEqual([]);
  });

  it("has no duplicate ids", () => {
    const ids = mappedIds();
    const seen = new Set<string>();
    const duplicates = ids.filter((id) => !seen.add(id));

    expect(duplicates).toEqual([]);
  });

  it("points every id at its own file", () => {
    const source = readFileSync(indexPath, "utf-8");
    const mismatched = [
      ...source.matchAll(
        /^\s*"([^"]+)":\s*\(\)\s*=>\s*import\("\.\/ui\/([^"]+)"\)/gm,
      ),
    ]
      .filter(([, id, target]) => id !== target)
      .map(([, id, target]) => `${id} -> ${target}`);

    expect(mismatched).toEqual([]);
  });

  // `iconSide` on 5 components and `iconPosition` on 9 were one prop with two
  // names, same `leading`/`trailing` values. Two names for one concept is the
  // shape of that bug, so the rule is stated rather than the pair banned.
  it("uses one name per concept across components", () => {
    const names = new Set<string>();
    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      for (const prop of meta.props ?? []) names.add(prop.name);
    }

    const byStem = new Map<string, string[]>();
    for (const name of names) {
      const stem = name.replace(/(Side|Position|Placement|Align)$/, "");
      if (stem === name) continue;
      byStem.set(stem, [...(byStem.get(stem) ?? []), name]);
    }

    const split = [...byStem.values()].filter((group) => group.length > 1);

    expect(split).toEqual([]);
  });

  // `"false"` is truthy, so a boolean default written as a string seeds the
  // playground with the prop switched on. Four components rendered disabled.
  it("declares boolean defaults as booleans", () => {
    const wrong: string[] = [];

    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      for (const prop of meta.props ?? []) {
        if (prop.type === "boolean" && typeof prop.default === "string") {
          wrong.push(`${file}: ${prop.name}`);
        }
      }
    }

    expect(wrong).toEqual([]);
  });

  // Same shape one level down: a schema can name any icon it likes, but
  // `resolveIcons` only knows the ones in `EXAMPLE_ICONS`, and an unknown name
  // resolves to `undefined` in silence - the toolbar's toggles simply did not
  // render, with nothing to say why.
  it("resolves every icon a schema names", () => {
    const known = new Set(
      (
        readFileSync(join(rootDir, "src/utils/demo.tsx"), "utf-8").match(
          /export const EXAMPLE_ICONS[^{]*\{[^}]*\}[^{]*\{([^}]*)\}/,
        )?.[1] ?? ""
      )
        .split(",")
        .map((entry) => entry.trim())
        .filter(Boolean),
    );

    expect(known.size).toBeGreaterThan(0);

    const named: string[] = [];
    const walk = (value: unknown) => {
      if (Array.isArray(value)) return value.forEach(walk);
      if (typeof value !== "object" || value === null) return;
      const marker = (value as Record<string, unknown>).$icon;
      if (typeof marker === "string") named.push(marker);
      for (const nested of Object.values(value)) walk(nested);
    };

    const missing: string[] = [];
    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      named.length = 0;
      walk(meta);
      for (const name of named) {
        if (!known.has(name)) missing.push(`${file}: ${name}`);
      }
    }

    expect(missing).toEqual([]);
  });

  // The snippet prints whatever `childrenExample` names, but the stage can only
  // render a component in `CHILD_COMPONENTS`. A name in one and not the other
  // is the code block lying again, in the other direction.
  it("renders every child the snippet prints", () => {
    const known = new Set(
      (
        readFileSync(join(rootDir, "src/utils/demo.tsx"), "utf-8").match(
          /const CHILD_COMPONENTS[^{]*\{([^}]*)\}/,
        )?.[1] ?? ""
      )
        .split(",")
        .map((entry) => entry.trim())
        .filter(Boolean),
    );

    const missing: string[] = [];
    for (const file of readdirSync(join(rootDir, "src/registry/meta"))) {
      const meta = JSON.parse(
        readFileSync(join(rootDir, "src/registry/meta", file), "utf-8"),
      );
      for (const child of meta.childrenExample ?? []) {
        if (!known.has(child.component))
          missing.push(`${file}: ${child.component}`);
      }
    }

    expect(missing).toEqual([]);
  });

  it("is not empty", () => {
    expect(mappedIds().length).toBeGreaterThan(0);
  });
});
